// Code generated by protoc-gen-go.
// source: log.proto
// DO NOT EDIT!

package mesos_internal_log

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Action_Type int32

const (
	Action_NOP      Action_Type = 1
	Action_APPEND   Action_Type = 2
	Action_TRUNCATE Action_Type = 3
)

var Action_Type_name = map[int32]string{
	1: "NOP",
	2: "APPEND",
	3: "TRUNCATE",
}
var Action_Type_value = map[string]int32{
	"NOP":      1,
	"APPEND":   2,
	"TRUNCATE": 3,
}

func (x Action_Type) Enum() *Action_Type {
	p := new(Action_Type)
	*p = x
	return p
}
func (x Action_Type) String() string {
	return proto.EnumName(Action_Type_name, int32(x))
}
func (x Action_Type) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Action_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Action_Type_value, data, "Action_Type")
	if err != nil {
		return err
	}
	*x = Action_Type(value)
	return nil
}

type Metadata_Status int32

const (
	Metadata_VOTING     Metadata_Status = 1
	Metadata_RECOVERING Metadata_Status = 2
	Metadata_STARTING   Metadata_Status = 3
	Metadata_EMPTY      Metadata_Status = 4
)

var Metadata_Status_name = map[int32]string{
	1: "VOTING",
	2: "RECOVERING",
	3: "STARTING",
	4: "EMPTY",
}
var Metadata_Status_value = map[string]int32{
	"VOTING":     1,
	"RECOVERING": 2,
	"STARTING":   3,
	"EMPTY":      4,
}

func (x Metadata_Status) Enum() *Metadata_Status {
	p := new(Metadata_Status)
	*p = x
	return p
}
func (x Metadata_Status) String() string {
	return proto.EnumName(Metadata_Status_name, int32(x))
}
func (x Metadata_Status) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Metadata_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Metadata_Status_value, data, "Metadata_Status")
	if err != nil {
		return err
	}
	*x = Metadata_Status(value)
	return nil
}

type Record_Type int32

const (
	Record_PROMISE  Record_Type = 1
	Record_ACTION   Record_Type = 2
	Record_METADATA Record_Type = 3
)

var Record_Type_name = map[int32]string{
	1: "PROMISE",
	2: "ACTION",
	3: "METADATA",
}
var Record_Type_value = map[string]int32{
	"PROMISE":  1,
	"ACTION":   2,
	"METADATA": 3,
}

func (x Record_Type) Enum() *Record_Type {
	p := new(Record_Type)
	*p = x
	return p
}
func (x Record_Type) String() string {
	return proto.EnumName(Record_Type_name, int32(x))
}
func (x Record_Type) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Record_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Record_Type_value, data, "Record_Type")
	if err != nil {
		return err
	}
	*x = Record_Type(value)
	return nil
}

type Promise struct {
	Proposal         *uint64 `protobuf:"varint,1,req,name=proposal" json:"proposal,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Promise) Reset()         { *m = Promise{} }
func (m *Promise) String() string { return proto.CompactTextString(m) }
func (*Promise) ProtoMessage()    {}

func (m *Promise) GetProposal() uint64 {
	if m != nil && m.Proposal != nil {
		return *m.Proposal
	}
	return 0
}

type Action struct {
	Position         *uint64          `protobuf:"varint,1,req,name=position" json:"position,omitempty"`
	Promised         *uint64          `protobuf:"varint,2,req,name=promised" json:"promised,omitempty"`
	Performed        *uint64          `protobuf:"varint,3,opt,name=performed" json:"performed,omitempty"`
	Learned          *bool            `protobuf:"varint,4,opt,name=learned" json:"learned,omitempty"`
	Type             *Action_Type     `protobuf:"varint,5,opt,name=type,enum=mesos.internal.log.Action_Type" json:"type,omitempty"`
	Nop              *Action_Nop      `protobuf:"bytes,6,opt,name=nop" json:"nop,omitempty"`
	Append           *Action_Append   `protobuf:"bytes,7,opt,name=append" json:"append,omitempty"`
	Truncate         *Action_Truncate `protobuf:"bytes,8,opt,name=truncate" json:"truncate,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}

func (m *Action) GetPosition() uint64 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

func (m *Action) GetPromised() uint64 {
	if m != nil && m.Promised != nil {
		return *m.Promised
	}
	return 0
}

func (m *Action) GetPerformed() uint64 {
	if m != nil && m.Performed != nil {
		return *m.Performed
	}
	return 0
}

func (m *Action) GetLearned() bool {
	if m != nil && m.Learned != nil {
		return *m.Learned
	}
	return false
}

func (m *Action) GetType() Action_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Action) GetNop() *Action_Nop {
	if m != nil {
		return m.Nop
	}
	return nil
}

func (m *Action) GetAppend() *Action_Append {
	if m != nil {
		return m.Append
	}
	return nil
}

func (m *Action) GetTruncate() *Action_Truncate {
	if m != nil {
		return m.Truncate
	}
	return nil
}

type Action_Nop struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Action_Nop) Reset()         { *m = Action_Nop{} }
func (m *Action_Nop) String() string { return proto.CompactTextString(m) }
func (*Action_Nop) ProtoMessage()    {}

type Action_Append struct {
	Bytes            []byte `protobuf:"bytes,1,req,name=bytes" json:"bytes,omitempty"`
	Cksum            []byte `protobuf:"bytes,2,opt,name=cksum" json:"cksum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Action_Append) Reset()         { *m = Action_Append{} }
func (m *Action_Append) String() string { return proto.CompactTextString(m) }
func (*Action_Append) ProtoMessage()    {}

func (m *Action_Append) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *Action_Append) GetCksum() []byte {
	if m != nil {
		return m.Cksum
	}
	return nil
}

type Action_Truncate struct {
	To               *uint64 `protobuf:"varint,1,req,name=to" json:"to,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Action_Truncate) Reset()         { *m = Action_Truncate{} }
func (m *Action_Truncate) String() string { return proto.CompactTextString(m) }
func (*Action_Truncate) ProtoMessage()    {}

func (m *Action_Truncate) GetTo() uint64 {
	if m != nil && m.To != nil {
		return *m.To
	}
	return 0
}

type Metadata struct {
	Status           *Metadata_Status `protobuf:"varint,1,req,name=status,enum=mesos.internal.log.Metadata_Status,def=4" json:"status,omitempty"`
	Promised         *uint64          `protobuf:"varint,2,req,name=promised,def=0" json:"promised,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}

const Default_Metadata_Status Metadata_Status = Metadata_EMPTY
const Default_Metadata_Promised uint64 = 0

func (m *Metadata) GetStatus() Metadata_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Default_Metadata_Status
}

func (m *Metadata) GetPromised() uint64 {
	if m != nil && m.Promised != nil {
		return *m.Promised
	}
	return Default_Metadata_Promised
}

type Record struct {
	Type             *Record_Type `protobuf:"varint,1,req,name=type,enum=mesos.internal.log.Record_Type" json:"type,omitempty"`
	Promise          *Promise     `protobuf:"bytes,2,opt,name=promise" json:"promise,omitempty"`
	Action           *Action      `protobuf:"bytes,3,opt,name=action" json:"action,omitempty"`
	Metadata         *Metadata    `protobuf:"bytes,4,opt,name=metadata" json:"metadata,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}

func (m *Record) GetType() Record_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Record) GetPromise() *Promise {
	if m != nil {
		return m.Promise
	}
	return nil
}

func (m *Record) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *Record) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type PromiseRequest struct {
	Proposal         *uint64 `protobuf:"varint,1,req,name=proposal" json:"proposal,omitempty"`
	Position         *uint64 `protobuf:"varint,2,opt,name=position" json:"position,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PromiseRequest) Reset()         { *m = PromiseRequest{} }
func (m *PromiseRequest) String() string { return proto.CompactTextString(m) }
func (*PromiseRequest) ProtoMessage()    {}

func (m *PromiseRequest) GetProposal() uint64 {
	if m != nil && m.Proposal != nil {
		return *m.Proposal
	}
	return 0
}

func (m *PromiseRequest) GetPosition() uint64 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

type PromiseResponse struct {
	Okay             *bool   `protobuf:"varint,1,req,name=okay" json:"okay,omitempty"`
	Proposal         *uint64 `protobuf:"varint,2,req,name=proposal" json:"proposal,omitempty"`
	Position         *uint64 `protobuf:"varint,4,opt,name=position" json:"position,omitempty"`
	Action           *Action `protobuf:"bytes,3,opt,name=action" json:"action,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PromiseResponse) Reset()         { *m = PromiseResponse{} }
func (m *PromiseResponse) String() string { return proto.CompactTextString(m) }
func (*PromiseResponse) ProtoMessage()    {}

func (m *PromiseResponse) GetOkay() bool {
	if m != nil && m.Okay != nil {
		return *m.Okay
	}
	return false
}

func (m *PromiseResponse) GetProposal() uint64 {
	if m != nil && m.Proposal != nil {
		return *m.Proposal
	}
	return 0
}

func (m *PromiseResponse) GetPosition() uint64 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

func (m *PromiseResponse) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type WriteRequest struct {
	Proposal         *uint64          `protobuf:"varint,1,req,name=proposal" json:"proposal,omitempty"`
	Position         *uint64          `protobuf:"varint,2,req,name=position" json:"position,omitempty"`
	Learned          *bool            `protobuf:"varint,3,opt,name=learned" json:"learned,omitempty"`
	Type             *Action_Type     `protobuf:"varint,4,req,name=type,enum=mesos.internal.log.Action_Type" json:"type,omitempty"`
	Nop              *Action_Nop      `protobuf:"bytes,5,opt,name=nop" json:"nop,omitempty"`
	Append           *Action_Append   `protobuf:"bytes,6,opt,name=append" json:"append,omitempty"`
	Truncate         *Action_Truncate `protobuf:"bytes,7,opt,name=truncate" json:"truncate,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}

func (m *WriteRequest) GetProposal() uint64 {
	if m != nil && m.Proposal != nil {
		return *m.Proposal
	}
	return 0
}

func (m *WriteRequest) GetPosition() uint64 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

func (m *WriteRequest) GetLearned() bool {
	if m != nil && m.Learned != nil {
		return *m.Learned
	}
	return false
}

func (m *WriteRequest) GetType() Action_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *WriteRequest) GetNop() *Action_Nop {
	if m != nil {
		return m.Nop
	}
	return nil
}

func (m *WriteRequest) GetAppend() *Action_Append {
	if m != nil {
		return m.Append
	}
	return nil
}

func (m *WriteRequest) GetTruncate() *Action_Truncate {
	if m != nil {
		return m.Truncate
	}
	return nil
}

type WriteResponse struct {
	Okay             *bool   `protobuf:"varint,1,req,name=okay" json:"okay,omitempty"`
	Proposal         *uint64 `protobuf:"varint,2,req,name=proposal" json:"proposal,omitempty"`
	Position         *uint64 `protobuf:"varint,3,req,name=position" json:"position,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WriteResponse) Reset()         { *m = WriteResponse{} }
func (m *WriteResponse) String() string { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()    {}

func (m *WriteResponse) GetOkay() bool {
	if m != nil && m.Okay != nil {
		return *m.Okay
	}
	return false
}

func (m *WriteResponse) GetProposal() uint64 {
	if m != nil && m.Proposal != nil {
		return *m.Proposal
	}
	return 0
}

func (m *WriteResponse) GetPosition() uint64 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

type LearnedMessage struct {
	Action           *Action `protobuf:"bytes,1,req,name=action" json:"action,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LearnedMessage) Reset()         { *m = LearnedMessage{} }
func (m *LearnedMessage) String() string { return proto.CompactTextString(m) }
func (*LearnedMessage) ProtoMessage()    {}

func (m *LearnedMessage) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type RecoverRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RecoverRequest) Reset()         { *m = RecoverRequest{} }
func (m *RecoverRequest) String() string { return proto.CompactTextString(m) }
func (*RecoverRequest) ProtoMessage()    {}

type RecoverResponse struct {
	Status           *Metadata_Status `protobuf:"varint,1,req,name=status,enum=mesos.internal.log.Metadata_Status" json:"status,omitempty"`
	Begin            *uint64          `protobuf:"varint,2,opt,name=begin" json:"begin,omitempty"`
	End              *uint64          `protobuf:"varint,3,opt,name=end" json:"end,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *RecoverResponse) Reset()         { *m = RecoverResponse{} }
func (m *RecoverResponse) String() string { return proto.CompactTextString(m) }
func (*RecoverResponse) ProtoMessage()    {}

func (m *RecoverResponse) GetStatus() Metadata_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *RecoverResponse) GetBegin() uint64 {
	if m != nil && m.Begin != nil {
		return *m.Begin
	}
	return 0
}

func (m *RecoverResponse) GetEnd() uint64 {
	if m != nil && m.End != nil {
		return *m.End
	}
	return 0
}

func init() {
	proto.RegisterEnum("mesos.internal.log.Action_Type", Action_Type_name, Action_Type_value)
	proto.RegisterEnum("mesos.internal.log.Metadata_Status", Metadata_Status_name, Metadata_Status_value)
	proto.RegisterEnum("mesos.internal.log.Record_Type", Record_Type_name, Record_Type_value)
}
